/**
 * One-time setup: create a 1Claw agent and write ONECLAW_AGENT_ID and
 * ONECLAW_AGENT_API_KEY to .env. Uses your user API key (from .env or env).
 *
 * Run: npm run setup
 * Prereq: Set ONECLAW_API_KEY in .env (get it from https://1claw.xyz/settings/api-keys)
 */
import "./load-env.js";
import { createClient } from "@1claw/sdk";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(__dirname, "..");
const envPath = join(packageRoot, ".env");

const BASE_URL = (process.env.ONECLAW_API_URL || process.env.ONECLAW_BASE_URL || "https://api.1claw.xyz").trim();
const USER_API_KEY = (process.env.ONECLAW_API_KEY ?? "").trim();

function isPlaceholder(key: string): boolean {
  return !key || key === "ocv_your_key_here" || key.startsWith("ocv_your_");
}

async function main() {
  console.log("Shroud demo — env setup\n");

  if (!USER_API_KEY || isPlaceholder(USER_API_KEY)) {
    console.log("You need a 1Claw user API key to create an agent.");
    console.log("");
    console.log("1. Open https://1claw.xyz and log in");
    console.log("2. Go to Settings → API Keys");
    console.log("3. Create an API key (or copy an existing one)");
    console.log("4. Add it to .env in this directory:");
    console.log("");
    console.log("   ONECLAW_API_KEY=ocv_...");
    console.log("");
    console.log("Then run: npm run setup");
    console.log("");
    process.exit(1);
  }

  const client = createClient({ baseUrl: BASE_URL });
  const authRes = await client.auth.apiKeyToken({ api_key: USER_API_KEY });
  if (authRes.error) {
    console.error("Auth failed:", authRes.error.message);
    process.exit(1);
  }

  const createRes = await client.agents.create({
    name: "shroud-demo-agent",
    description: "Created by examples/shroud-demo setup",
    intents_api_enabled: true,
    scopes: ["vault.read"],
  });

  if (createRes.error || !createRes.data) {
    console.error("Create agent failed:", createRes.error?.message ?? "no data");
    process.exit(1);
  }

  const { agent, api_key } = createRes.data;
  if (!api_key) {
    console.error("Agent created but no API key returned (auth_method may not be api_key).");
    process.exit(1);
  }

  console.log("Agent created:");
  console.log("  ID:", agent.id);
  console.log("  Name:", agent.name);
  console.log("  API key:", api_key.slice(0, 12) + "...");
  console.log("");

  let envContent: string;
  if (existsSync(envPath)) {
    envContent = readFileSync(envPath, "utf-8");
    envContent = envContent.replace(
      /^ONECLAW_AGENT_ID=.*/m,
      `ONECLAW_AGENT_ID=${agent.id}`
    );
    envContent = envContent.replace(
      /^ONECLAW_AGENT_API_KEY=.*/m,
      `ONECLAW_AGENT_API_KEY=${api_key}`
    );
  } else {
    envContent = `# Generated by npm run setup
ONECLAW_SHROUD_URL=https://shroud.1claw.xyz
ONECLAW_API_URL=${BASE_URL}
ONECLAW_AGENT_ID=${agent.id}
ONECLAW_AGENT_API_KEY=${api_key}
`;
  }

  writeFileSync(envPath, envContent, "utf-8");
  console.log("Updated", envPath, "with ONECLAW_AGENT_ID and ONECLAW_AGENT_API_KEY.");
  console.log("");
  console.log("Run: npm start");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
